### ISSUE TITLE
fatal: not a git repository (or any parent up to mount point /tf) Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set). Error /tf/rover/functions.sh on or near line landingzone folder not setup properly. Fix and restart.; exiting with status 1[bug]

### ISSUE THREAD

**Issue by Herminder39** [Azure/caf-terraform-landingzones#479]
I need to run CAF terraform landing zone for my production environment & testing the given script however unable to run & getting below error while running. If the steps below are wrong, can you guide me on how to run or resolve it? Also, as per the video (https://www.youtube.com/watch?v=w0W90bqZaWA&list=PLU8D1GcHfTRoYHqVUV856zZ4q3ZgxWiKg&index=3) landing zone folder also not available. I think that is 2 years OLD so might be some changes. I also tried via (rover --walkthrough) however that also failed.  I can share screenshot if you provide any mail ID?

 rover -lz /tf/caf/caf_launchpad \
  -launchpad \
  -var-folder /tf/caf/caf_launchpad/scenario/100 \
  -env test \
  -a plan

fatal: not a git repository (or any parent up to mount point /tf)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Error /tf/rover/functions.sh on or near line landingzone folder not setup properly. Fix and restart.; exiting with status 1
No terraform cloud runs found.
@calling clean_up_variables
cleanup variables
clean_up backend_files
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
 - OS and version: [e.g. Windows 10 1909]
 - Version of the rover[e.g. 22]
 - Version of the landing zone[e.g. 11]

**Additional context**

**Comment by Herminder39** [comment]
Plan: 18 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  ~ global_settings = (sensitive value)
╷
│ Warning: Argument is deprecated
│ 
│   with module.launchpad.module.api_management_custom_domain.azurerm_api_management_custom_domain.apim,
│   on /home/vscode/.terraform.cache/sandpit/modules/launchpad/modules/apim/api_management_custom_domain/module.tf line 1, in resource "azurerm_api_management_custom_domain" "apim":
│    1: resource "azurerm_api_management_custom_domain" "apim" {
│ 
│ `proxy` is deprecated and will be renamed to `gateway` in version 3.0 of the AzureRM provider
╵
╷
│ Error: building AzureRM Client: please ensure you have installed Azure CLI version 2.0.79 or newer. Error parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: Could not import runpy module
│ Traceback (most recent call last):
│   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
│   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
│   File "<frozen importlib._bootstrap>", line 945, in _find_spec
│   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
│   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec
│   File "<frozen importlib._bootstrap_external>", line 1548, in find_spec
│   File "<frozen importlib._bootstrap_external>", line 1591, in _fill_cache
│ OSError: [Errno 12] Cannot allocate memory: '/tf/caf/caf_launchpad'.
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 30, in provider "azurerm":
│   30: provider "azurerm" {
│ 
╵
╷
│ Error: Building AzureAD Client
│ 
│   with provider["registry.terraform.io/hashicorp/azuread"],
│   on main.tf line 84, in provider "azuread":
│   84: provider "azuread" {
│ 
│ Please ensure you have installed Azure CLI version 2.0.81 or newer. Error parsing json result from the Azure CLI: Error waiting for the Azure CLI:
│ exit status 1: Could not import runpy module
│ Traceback (most recent call last):
│   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
│   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
│   File "<frozen importlib._bootstrap>", line 945, in _find_spec
│   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
│   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec
│   File "<frozen importlib._bootstrap_external>", line 1548, in find_spec
│   File "<frozen importlib._bootstrap_external>", line 1591, in _fill_cache
│ OSError: [Errno 12] Cannot allocate memory: '/tf/caf/caf_launchpad'.
╵
Terraform plan return code: 1
Error 1 on or near line 57: Error running terraform plan; exiting with status 1

@calling clean_up_variables
cleanup variables

**Comment by Herminder39** [comment]
Via /tf/caf/caf_launchpad/scenario/100 \ & /tf/caf/caf_launchpad/scenario/200, after running the script, I can see Storage
Key vault, Manage identity deployment successfully. I would like to know if ONLY these resources should deploy or just because the landing zone folder is missing, other resources were not deployed.
